routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('books.home');
});
Route::get('/contact', function () {
    return view('books.contact');
});
Route::get('/about', function () {
    return view('books.about');
});
Route::get('/login','sessioncontroller@create' );
Route::post('/login','sessioncontroller@store' )->name('login.form');
Route::get('/register','registercontroller@create' );
Route::post('/register','registercontroller@store' )->name('register.form');
Route::get('/logout','sessioncontroller@destroy' );
Route::get('/books','bookcontroller@show_all' );
Route::get('/books/show/{id}','bookcontroller@show' )->name('book.show');
Route::get('/authors','authorcontroller@show_all' );
Route::get('/authors/show/{id}', 'authorcontroller@show')->name('author.show');
Route::get('/category/show/{id}', 'categorycontroller@show')->name('category.show');
Route::get('/admin/logout','sessioncontroller@destroy' );
Route::resource('admin/categories', 'categorycontroller');
Route::resource('admin/authors', 'authorcontroller');
Route::resource('admin/books', 'bookcontroller');
Route::resource('admin/users', 'usercontroller');

Route::get('/admin', function () {
    return view('admin.dash');
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function category()
    {
        return $this->belongsTo(Categories::class);
    }
    public function author()
    {
        return $this->belongsTo(Author::class);
    }
    protected $dates = ['published_at'];
}

app/Http/Controllers/bookcontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categories;
use App\Author;
use App\User;
use App\Book;

class bookcontroller extends Controller
{
    public function show_all()
    {
        $books = Book::all();

        return view('books.book', compact('books'));
    }
    public function show($id)
    {
        $book = Book::find($id);
        $cats = Categories::all();

        return view('books.book_detail', compact('book','cats'));
    }
    public function index()
    {
        $books = Book::all();

        return view('admin.books.index', compact('books'));
    }
    public function create()
    {
        $categories = Categories::all();
        $authors = Author::all();
        return view('admin.books.create', compact('categories','authors'));

    }
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'description'=>'required',
            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'author'=>'required',
            'cat'=>'required',
            'sn'=>'required',
        ]);
        $imageName = time().'.'.$request->photo->getClientOriginalExtension();
        $request->photo->move(public_path('images'), $imageName);

        $book = new Book ;
        $book->title = $request->get('title');
        $book->description = $request->get('description');
        $book->photo = 'images/'.$imageName;
        $book->author_id = $request->get('author');
        $book->category_id = $request->get('cat');
        $book->author_type = 'App\Author';
        $book->category_type = 'App\Categories';
        $book->user_id = '1';
        $book->published_at = now();
        $book->publish_sn = $request->get('sn');
        $book->save();
        return redirect('/admin/books/')->with('success', 'Book has been added');
    }
    public function edit($id)
    {
        $book = Book::find($id);
        $categories = Categories::all();
        $authors = Author::all();

        return view('admin.books.edit', compact('book','categories','authors'));
    }
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'description'=>'required',
            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'author'=>'required',
            'cat'=>'required',
            'sn'=>'required',

        ]);
        $imageName = time().'.'.$request->photo->getClientOriginalExtension();
        $request->photo->move(public_path('images'), $imageName);

        $book = Book::find($id);
        $book->title = $request->get('title');
        $book->description = $request->get('description');
        $book->photo = 'images/'.$imageName;
        $book->author_id = $request->get('author');
        $book->category_id = $request->get('cat');
        $book->user_id = '1';
        $book->published_at = now();
        $book->publish_sn = $request->get('sn');
        $book->save();

        return redirect('/admin/books')->with('success', 'Book has been updated');
    }
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();

        return redirect('/admin/books')->with('success', 'Book has been deleted Successfully');
    }
}

resources/views/admin/books/create.blade.php
@extends('layouts_admin.header')
@section('content')
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item">Items</li>
        <li class="breadcrumb-item"><a href="#">Books</a></li>
    </ul>
    </div>
    <form method="post" action="{{ route('books.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="tile">

            <h3 class="title" align="center">New Book</h3><br>


            <div class="tile-body">
                <input class="form-control" id="" name="title" type="text" placeholder="Enter Book Title ..">
            </div>
            <br>
            <div class="tile-body">
                <textarea class="form-control" id="" name="description" type="text" placeholder="Enter Book Description .."></textarea>
            </div>
            <br>
            <div class="tile-body">
                <input class="form-control" id="" name="photo" type="file">
            </div>
            <br>
            <div class="" >
                <select name="author" id="" style="padding: 10px; border-radius: 10px;">
                    @foreach($authors as $author)
                        <option value="{{$author->id}}"> {{$author->name}} </option>
                    @endforeach
                </select>
            </div>
            <br>
            <div class="" >
                <select name="cat" id="" style="padding: 10px; border-radius: 10px;" >
                    @foreach($categories as $category)
                    <option value="{{$category->id}}"> {{$category->name}} </option>
                    @endforeach
                </select>
            </div>
            <br>
            <div class="tile-body">
                <input class="form-control" id="" name="sn" type="text" placeholder="Enter Book Serial Number ..">
            </div>
            <br>

            <div class="tile-footer" align="center">
                <button class="btn btn-primary" name="submit" type="submit"> Add </button>
            </div>



        </div>
        @include('layouts_admin.error')
    </form>
@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts_admin.header')
@section('content')
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item">Items</li>
        <li class="breadcrumb-item"><a href="#">Books</a></li>
    </ul>
    </div>
    <form method="post" action="{{ route('books.update', $book->id) }}" enctype="multipart/form-data">
        @method('PATCH')
        @csrf
        <div class="tile">

            <h3 class="title" align="center">Edit Book</h3><br>


            <div class="tile-body">
                <input class="form-control" id="" name="title" type="text" value={{ $book->title }}>
            </div>
            <br>
            <div class="tile-body">
                <textarea class="form-control" id="" name="description" type="text">{{ $book->description }}</textarea>
            </div>
            <br>
            <div class="tile-body">
                <input class="form-control" id="" name="photo" type="file" value={{ $book->photo }}>
            </div>
            <br>
            <div class="" >
                <select name="author" id="" style="padding: 10px; border-radius: 10px;">
                    @foreach($authors as $author)
                        <option value="{{$author->id}}"> {{$author->name}} </option>
                    @endforeach
                </select>
            </div>
            <br>
            <div class="" >
                <select name="cat" id="" style="padding: 10px; border-radius: 10px;" >
                    @foreach($categories as $category)
                        <option value="{{$category->id}}"> {{$category->name}} </option>
                    @endforeach
                </select>
            </div>
            <br>
            <div class="tile-body">
                <input class="form-control" id="" name="sn" type="text" value={{ $book->publish_sn }}>
            </div>
            <br>

            <div class="tile-footer" align="center">
                <button class="btn btn-primary" name="submit" type="submit"> Edit </button>
            </div>



        </div>
        @include('layouts_admin.error')
    </form>
@endsection

resources/views/admin/books/index.blade.php
@extends('layouts_admin.header')

@section('content')

    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item">Items</li>
        <li class="breadcrumb-item active"><a href="#">Books</a></li>
    </ul>
    </div>
    <p align="center"><a class="btn btn-primary icon-btn" href="{{url ('/admin/books/create')}}"><i class="fa fa-plus"></i>Add Book	</a></p>
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br />
    @endif
    <div style="margin:10px; padding:10px;">
        <div class="row">
            <div class="col-md-12">
                <div class="tile">
                    <div class="tile-body">
                        <table class="table table-hover table-bordered" id="sampleTable">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Photo</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>SN</th>
                                <th>Action</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($books as $book)

                                <tr>
                                    <td>{{$book->title}}</td>
                                    <td>{{$book->description}}</td>
                                    <td><img style="width: 100px ; height: 100px " src="{{ asset($book->photo)}}" ></td>
                                    <td>{{$book->author->name}}</td>
                                    <td>{{$book->category->name}}</td>
                                    <td>{{$book->publish_sn}}</td>
                                    <td>
                                        <div align="center" >
                                            <div class="btn-group">
                                                <form>
                                                    <a class="btn btn-primary" href="{{ route('books.edit',$book->id)}}">
                                                        <i class="fa fa-lg fa-edit"></i>
                                                    </a>
                                                </form>

                                                <form action="{{ route('books.destroy', $book->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn btn-danger" type="submit">

                                                        <i class="fa fa-lg fa-trash"></i>

                                                    </button>

                                                </form>
                                            </div>

                                        </div>
                                    </td>

                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
<html>
<body >
<main>
</main>
<!-- Essential javascripts for application to work-->
<script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{{ asset('js/plugins/pace.min.js') }}"></script>
<!-- Page specific javascripts-->
<!-- Data table plugin-->
<script type="text/javascript" src="{{ asset('js/plugins/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/dataTables.bootstrap.min.js') }}"></script>
<script type="text/javascript">$('#sampleTable').DataTable();</script>
<!-- Google analytics script-->
<script type="text/javascript">
    if(document.location.hostname == 'pratikborsadiya.in') {
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-72504830-1', 'auto');
        ga('send', 'pageview');
    }
</script>
</body>
</html>