routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('books.home');
});
Route::get('/contact', function () {
    return view('books.contact');
});
Route::get('/about', function () {
    return view('books.about');
});
Route::get('/login','sessioncontroller@create' );
Route::post('/login','sessioncontroller@store' )->name('login.form');
Route::get('/register','registercontroller@create' );
Route::post('/register','registercontroller@store' )->name('register.form');
Route::get('/logout','sessioncontroller@destroy' );
Route::get('/books','bookcontroller@show_all' );
Route::get('/books/show/{id}','bookcontroller@show' )->name('book.show');
Route::get('/authors','authorcontroller@show_all' );
Route::get('/authors/show/{id}', 'authorcontroller@show')->name('author.show');
Route::get('/category/show/{id}', 'categorycontroller@show')->name('category.show');
Route::get('/admin/logout','sessioncontroller@destroy' );
Route::resource('admin/categories', 'categorycontroller');
Route::resource('admin/authors', 'authorcontroller');
Route::resource('admin/books', 'bookcontroller');
Route::resource('admin/users', 'usercontroller');

Route::get('/admin', function () {
    return view('admin.dash');
});

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    public function books(){
        return $this->morphMany(Book::class, 'author');
    }
}

app/Http/Controllers/authorcontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Author;

class authorcontroller extends Controller
{
    public function show_all()
    {
        $authors = Author::all();

        return view('books.author', compact('authors'));
    }
    public function show($id)
    {
        $author = Author::find($id);

        return view('books.author_detail', compact('author'));
    }
    public function index()
    {
        $authors = Author::all();

        return view('admin.authors.index', compact('authors'));
    }
    public function create()
    {
        return view('admin.authors.create');
    }
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required',
        ]);
        $author = new Author ;
        $author->name = $request->get('name');
        $author->description = $request->get('description');
        $author->save();
        return redirect('/admin/authors')->with('success', 'Author has been added');
    }
    public function edit($id)
    {
        $author = Author::find($id);

        return view('admin.authors.edit', compact('author'));
    }
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required',

        ]);

        $author = Author::find($id);
        $author->name = $request->get('name');
        $author->description = $request->get('description');
        $author->save();

        return redirect('/admin/authors')->with('success', 'Author has been updated');
    }
    public function destroy($id)
    {
        $author = Author::find($id);
        $author->delete();

        return redirect('/admin/authors')->with('success', 'Author has been deleted Successfully');
    }

}

resources/views/admin/authors/create.blade.php
@extends('layouts_admin.header')
@section('content')
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item">Items</li>
        <li class="breadcrumb-item"><a href="#">Authors</a></li>
    </ul>
    </div>
    <form method="post" action="{{ route('authors.store') }}">
        @csrf
        <div class="tile">

            <h3 class="title" align="center">New Author</h3><br>


            <div class="tile-body">
                <input class="form-control" id="" name="name" type="text" placeholder="Enter Author Name ..">
            </div>
            <br>
            <div class="tile-body">
                <textarea class="form-control" id="" name="description" type="text" placeholder="Enter Author Description .."></textarea>
            </div>
            <div class="tile-footer" align="center">
                <button class="btn btn-primary" name="submit" type="submit"> Add </button>
            </div>



        </div>
        @include('layouts_admin.error')
    </form>
@endsection

resources/views/admin/authors/edit.blade.php
@extends('layouts_admin.header')
@section('content')
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item">Items</li>
        <li class="breadcrumb-item"><a href="#">Authors</a></li>
    </ul>
    </div>
    <form method="post" action="{{ route('authors.update', $author->id) }}">
        @method('PATCH')
        @csrf
        <div class="tile">

            <h3 class="title" align="center">Edit Category</h3>


            <div class="tile-body">
                <input class="form-control" id="" name="name" type="text" value={{ $author->name }}>
            </div>
            <br>
            <div class="tile-body">
                <textarea class="form-control" id="" name="description" type="text" >{{ $author->description }}</textarea>
            </div>
            <div class="tile-footer" align="center">
                <button class="btn btn-primary" name="submit" type="submit"> Edit </button>
            </div>



        </div>
        @include('layouts_admin.error')
    </form>
@endsection

resources/views/admin/authors/index.blade.php
@extends('layouts_admin.header')

@section('content')

    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item">Items</li>
        <li class="breadcrumb-item active"><a href="#">Authors</a></li>
    </ul>
    </div>
    <p align="center"><a class="btn btn-primary icon-btn" href="{{url ('/admin/authors/create')}}"><i class="fa fa-plus"></i>Add Author	</a></p>
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br />
    @endif
    <div style="margin:10px; padding:10px;">
        <div class="row">
            <div class="col-md-12">
                <div class="tile">
                    <div class="tile-body">
                        <table class="table table-hover table-bordered" id="sampleTable">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Action</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($authors as $author)

                                <tr>
                                    <td>{{$author->name}}</td>
                                    <td>{{$author->description}}</td>
                                    <td>
                                        <div align="center" >
                                            <div class="btn-group">
                                                <form>
                                                    <a class="btn btn-primary" href="{{ route('authors.edit',$author->id)}}">
                                                        <i class="fa fa-lg fa-edit"></i>
                                                    </a>
                                                </form>

                                                <form action="{{ route('authors.destroy', $author->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn btn-danger" type="submit">

                                                        <i class="fa fa-lg fa-trash"></i>

                                                    </button>

                                                </form>
                                            </div>

                                        </div>
                                    </td>

                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
<html>
<body >
<main>
</main>
<!-- Essential javascripts for application to work-->
<script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{{ asset('js/plugins/pace.min.js') }}"></script>
<!-- Page specific javascripts-->
<!-- Data table plugin-->
<script type="text/javascript" src="{{ asset('js/plugins/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/dataTables.bootstrap.min.js') }}"></script>
<script type="text/javascript">$('#sampleTable').DataTable();</script>
<!-- Google analytics script-->
<script type="text/javascript">
    if(document.location.hostname == 'pratikborsadiya.in') {
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-72504830-1', 'auto');
        ga('send', 'pageview');
    }
</script>
</body>
</html>